#cloud-config
# vim: syntax=yaml
#

# Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: yardengnome
manage_etc_hosts: true

# You could modify this for your own user information
users:
  - name: yg
    gecos: "Yarden Gnome"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video,input,systemd-journal
    plain_text_passwd: { <PASSWORD> }
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

# # Set the locale of the system
locale: "en_US.UTF-6"

# # Set the timezone
# # Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: "America/Chicago"

# # Update apt packages on first boot
package_update: true
package_upgrade: true
package_reboot_if_required: true

# # Install any additional apt packages you need here
packages:
  - raspberrypi-kernel-headers
  - build-essential
  - gitlab-runner
  - dkms
  - lshw

# These commands will be ran once on first boot only
runcmd:
  # Pickup the hostname changes
  - [systemctl restart avahi-daemon]
  # linux headers for drivers
  - [apt-get install linux-headers-$(uname -r)]
  # install wifi dongle drivers
  # - []
  # start ygwifi service
  - [
      docker run --name ygwifi \
      --sysctl net.ipv6.conf.all.disable_ipv6=1 \
      --restart always \
      --dns 8.8.8.8 \
      --dns 8.8.4.4 \
      ryazbeck/ygwifi:latest,
    ]
  # start yarden-gnome-button
  # - []
  # start yarden-gnome-station
  # - []
  # register gitlab runner
  - [
      export YGWIFI_ENV=prod &&,
      export PROJECT_REGISTRATION_TOKEN=<TOKEN HERE> &&,
      sudo gitlab-runner register,
      "--config /etc/gitlab-runner/config.toml",
      "--non-interactive",
      "--url 'https://gitlab.com/'",
      "--registration-token '$PROJECT_REGISTRATION_TOKEN'",
      "--executor 'shell'",
      "--description 'ygwifi-$YGWIFI_ENV'",
      "--tag-list '$YGWIFI_ENV'",
    ]
